# Generated by Django 5.1.7 on 2025-03-25 17:55

import django.core.validators
import tasks.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Task name must be at least 3 characters long.'), django.core.validators.MaxLengthValidator(200, 'Task name cannot exceed 200 characters.'), tasks.validators.validate_task_name])),
                ('description', models.TextField(blank=True, null=True, validators=[tasks.validators.validate_description_length])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('assigned_users', models.ManyToManyField(related_name='users_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
